<a href="https://colab.research.google.com/github/ShivinM-17/PyTorch-practices/blob/main/PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pytorch Introduction

In [5]:
import torch
torch.__version__

'2.0.1+cu118'

### Tensors

#### Creating tensors

**Scalar** - tensor with no dimension

In [6]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [7]:
# Retrieving the number from the tensor
scalar.item()

7

**Vector** - tensor with 1 dimension (can have many elements)

In [8]:
vector=torch.tensor([1,2,3,4])
vector

tensor([1, 2, 3, 4])

In [9]:
vector.ndim

1

In [10]:
# checking the shape of the vector
vector.shape

torch.Size([4])

This gives output as 4, since there are 4 elements in the tensor

**Matrix** - this is a series of different vectors, thus having dimension as 2

In [11]:
matrix=torch.tensor([[1,2],[2,3]])
matrix

tensor([[1, 2],
        [2, 3]])

In [12]:
# Checking the dimensions of the matrix
matrix.ndim

2

Output comes as 2, since we have made a 2x2 matrix, thus 2 dimensions

In [13]:
# Checking the shape of the matrix
matrix.shape

torch.Size([2, 2])

Output comes as [2,2] since we only have 2 row, which consists of 2 elements each

**Tensor** - tensors having n dimensions

In [14]:
TENSOR=torch.tensor([[1,2,3],
                     [2,3,4],
                     [3,4,5]])

In [15]:
TENSOR

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [16]:
# Checking the shape of the tensor
TENSOR.shape

torch.Size([3, 3])

In [18]:
# Checking the dimensions of the tensor
TENSOR.ndim

2

#### Random tensors

In [19]:
# Creating a random tensor of size(3,4)
random_tensor=torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.3065, 0.3592, 0.4898, 0.0284],
         [0.2644, 0.6477, 0.3683, 0.5563],
         [0.8208, 0.0948, 0.9225, 0.0053]]),
 torch.float32)

In [20]:
# Create a random tensor of size (224, 224, 3)
random_tensor=torch.rand(size=(224,224,3))
random_tensor, random_tensor.dtype

(tensor([[[0.1129, 0.2014, 0.0729],
          [0.7569, 0.6038, 0.1097],
          [0.9254, 0.2966, 0.3934],
          ...,
          [0.9061, 0.1714, 0.7553],
          [0.9560, 0.3770, 0.1861],
          [0.0909, 0.6581, 0.3811]],
 
         [[0.4523, 0.9102, 0.9384],
          [0.7032, 0.0899, 0.8657],
          [0.3260, 0.5907, 0.1219],
          ...,
          [0.6183, 0.8716, 0.2722],
          [0.0249, 0.7274, 0.3351],
          [0.9239, 0.6722, 0.7898]],
 
         [[0.5008, 0.0184, 0.8271],
          [0.3545, 0.1911, 0.1454],
          [0.5657, 0.4615, 0.2465],
          ...,
          [0.3150, 0.7879, 0.4120],
          [0.8010, 0.4748, 0.2513],
          [0.9397, 0.9675, 0.6743]],
 
         ...,
 
         [[0.5432, 0.0878, 0.6938],
          [0.7390, 0.0341, 0.5725],
          [0.2862, 0.6009, 0.8405],
          ...,
          [0.0225, 0.2350, 0.7639],
          [0.7710, 0.7177, 0.4450],
          [0.8736, 0.5070, 0.8522]],
 
         [[0.5971, 0.7629, 0.3409],
          [0

#### Zeros and Ones
Sometimes we require the tensors to be filled with just 0's and 1's, thus creating such tensors

In [21]:
# Create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones=torch.zeros(size=(3,4))
ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#### Tensors with range of numbers

Use ``torch.arange(start,end,step)`` to perform this.                           
**Note:-**torch.range() is a deprecated function

In [23]:
# Creating a tensor with range of numbers
tn_ranges=torch.arange(start=0,end=100,step=5)
tn_ranges

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [24]:
# Create a tensor similar to tn_ranges
tn_similar=torch.zeros_like(input=tn_ranges)
tn_similar

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor Datatypes
Default datatype of tensor - float32

In [27]:
# Creating the tensor with default tensor datatype
tens=torch.tensor([3.0, 6.0, 9.0],
                  dtype=None,  # defaults to None, i.e, float32
                  device=None, # defaults to None, which uses the default type
                  requires_grad=False) # if true, operations performed as recorded
tens, tens.shape, tens.dtype, tens.device

(tensor([3., 6., 9.]), torch.Size([3]), torch.float32, device(type='cpu'))

In [29]:
# Creating a tensor with float16 datatype
tens=torch.tensor([3.0, 6.0, 9.0],
                  dtype=torch.float16)
tens, tens.shape, tens.dtype, tens.ndim

(tensor([3., 6., 9.], dtype=torch.float16), torch.Size([3]), torch.float16, 1)

### Getting information from tensors
eg.- shape, dtype and device

In [30]:
# Creating a random tensor
tens=torch.rand(3,4)

# Getting the details of the tensor
print(tens)
print(f"Shape of the tensor is {tens.shape}")
print(f"Datatype of the tensor is {tens.dtype}")
print(f"Device tensor is stored on {tens.device}")

tensor([[0.5635, 0.9325, 0.5801, 0.3655],
        [0.1261, 0.1399, 0.2188, 0.0104],
        [0.6034, 0.5312, 0.0157, 0.6259]])
Shape of the tensor is torch.Size([3, 4])
Datatype of the tensor is torch.float32
Device tensor is stored on cpu


### Tensor operations

#### Performing operations
operations like addition, subtraction, multiplication, division, etc.

In [31]:
# Adding a number to a tensor
tens=torch.rand(3,4)
tens+10

tensor([[10.0790, 10.4467, 10.9160, 10.0118],
        [10.6188, 10.9013, 10.7313, 10.7023],
        [10.3311, 10.6848, 10.2263, 10.5454]])

In [33]:
# Multiplying a number to a tensor
tens*10

tensor([[0.7901, 4.4671, 9.1604, 0.1177],
        [6.1884, 9.0131, 7.3128, 7.0229],
        [3.3106, 6.8480, 2.2632, 5.4541]])

In [34]:
# Even after such operations, original tensor does not change
tens

tensor([[0.0790, 0.4467, 0.9160, 0.0118],
        [0.6188, 0.9013, 0.7313, 0.7023],
        [0.3311, 0.6848, 0.2263, 0.5454]])

In [35]:
# Subtracting values
tens=torch.tensor([1,2,3,4])
tens-10

tensor([-9, -8, -7, -6])

In [36]:
# Performing element-wise multiplication of the tensor
tens*tens

tensor([ 1,  4,  9, 16])

#### Matrix multiplication

* Element-wise multiplication - ``tensor*tensor``
* Matrix multiplication - ``torch.matmul(tensor, tensor)``

In [37]:
# Creating a tensor
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [38]:
# Element-wise matrix multiplication
tensor*tensor

tensor([1, 4, 9])

In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
# using @ to multiply
tensor @ tensor

tensor(14)

In [43]:
# Getting the time taken for multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 91 µs, sys: 4 µs, total: 95 µs
Wall time: 98.5 µs


tensor(14)

#### Shape errors in multiplication

In [44]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

This gives an error, since we can't multiply 2 (3x2) tensor.

Multiplication can only have, given that the matrices are of form (mxn) and (nxp)

In [45]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [46]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [47]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [49]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape},\n tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above),\n tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]),
 tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above),
 tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [50]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

#### Finding min, max, mean, sum, etc. (aggregation)

In [52]:
# Create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") --> will give an error
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [54]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

#### Positional min/max
Finding the index of the maximum or minimum occurance in a tensor

In [55]:
tensor=torch.arange(10,100,10)
print(f"Tensor: {tensor}")

# Returning index of maximum and minimum indexes
print(f"Minimum index: {tensor.argmin()}")
print(f"Maximum index: {tensor.argmax()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum index: 0
Maximum index: 8


#### Change tensor datatype

In [58]:
# Create a tensor
tensor=torch.arange(10., 100., 10.)  # float32 datatype
tensor.dtype

torch.float32

In [59]:
# Creating a float16 tensor
tens_16=tensor.type(torch.float16)
tens_16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [60]:
# Create a int8 tensor
tens_8=tensor.type(torch.int8)
tens_8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Reshaping, stacking, squeezing and unsqueezing

In [61]:
# Creating a tensor
import torch
x=torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Adding an extra dimension using ``torch.reshape()``

In [63]:
x_reshaped=x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Changing the view with ``torch.view()``

In [64]:
z=x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [65]:
x

tensor([1., 2., 3., 4., 5., 6., 7.])

**Note:-** Remember that using torch.view() also changes the original tensor

In [66]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

Stacking the tensor on top of itself, using ``torch.stack()``

In [67]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [68]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

Using ``torch.squeeze()`` to squeeze the tensor, i.e., changing the tensor to a dimension of 1

In [69]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


Using ``torch.unsqueeze()`` to unsqueeze the tensor

In [71]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

In [72]:
# Create tensor
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [73]:
# Doing bracket indexing
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [74]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [75]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [76]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [77]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

### PyTorch tensors and NumPy

Performing the following 2 conversions:
* NumPy array -> PyTorch tensor :- ``torch.from_numpy(ndarray)``
* PyTorch tensor -> NumPy array :- ``torch.Tensor.numpy()``

In [79]:
# Numpy array to Tensor
import torch
import numpy as np
array=np.arange(1.0, 8.0)
tensor=torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

**Note:** By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32)

In [80]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
# Tensor to NumPy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()  # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [83]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility
Getting to know more about randomness of numbers we can get using some functions

In [85]:
import torch
import random

# Setting the random seed
random_seed=42
torch.manual_seed(seed=random_seed)
random_tensor_C = torch.rand(3,4)

# An issue - seed is needed to be reset everytime rand() is called
torch.random.manual_seed(seed=random_seed)
random_tensor_D=torch.rand(3,4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running tensors on GPUs

In [86]:
!nvidia-smi

Fri Jul 21 19:40:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Currently, using the Tesla T4 GPU

#### Getting PyTorch to run on GPU

In [87]:
import torch
torch.cuda.is_available()

True

Since true, this means that PyTorch can use the GPU

In [90]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [88]:
# Getting count of devices using the GPU
torch.cuda.device_count()

1

#### Putting tensors on the GPU

In [91]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

Here `cuda:0` means that the tensor is stored on the 0th GPU avaible (0th indexed GPU)

#### Moving back to CPU

In [92]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: ignored

In [93]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [94]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')